"""add balance columns to imports

Revision ID: d7921ed1b928
Revises: d7cde46fca22
Create Date: 2026-05-29 15:12:04.537903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7921ed1b928'
down_revision: Union[str, Sequence[str], None] = 'd7cde46fca22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imports', sa.Column('ledger_balance', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('imports', sa.Column('ledger_balance_date', sa.Date(), nullable=True))
    op.add_column('imports', sa.Column('available_balance', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('imports', sa.Column('available_balance_date', sa.Date(), nullable=True))
    op.add_column('imports', sa.Column('beginning_balance', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imports', 'beginning_balance')
    op.drop_column('imports', 'available_balance_date')
    op.drop_column('imports', 'available_balance')
    op.drop_column('imports', 'ledger_balance_date')
    op.drop_column('imports', 'ledger_balance')
    # ### end Alembic commands ###
